/**
 * Generate TypeScript asset modules from rom/assets/ PNGs.
 *
 * Produces web/src/assets/tile-data.ts with font tiles, font widths,
 * soft font tiles, icon tiles, and default cover tiles as Uint8Array constants.
 *
 * Usage: npx tsx scripts/build-assets.ts
 */

import { writeFile, mkdir } from "fs/promises";
import { resolve, dirname, join } from "path";
import { fileURLToPath } from "url";
import { generateFont, generateSoftFont } from "../src/build/font.js";
import { generateIcons } from "../src/build/icons.js";
import { generateCover } from "../src/build/cover.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "..");
const ROM_DIR = join(PROJECT_ROOT, "rom");
const ASSET_DIR = join(ROM_DIR, "assets");
const OUTPUT_DIR = join(PROJECT_ROOT, "web", "src", "assets");

/** Format a Uint8Array as a TS constant definition. */
function toTsArray(name: string, data: Uint8Array): string {
  const lines: string[] = [];
  lines.push(`export const ${name} = new Uint8Array([`);

  // 16 bytes per line
  for (let i = 0; i < data.length; i += 16) {
    const end = Math.min(i + 16, data.length);
    const chunk = Array.from(data.slice(i, end))
      .map((b) => `0x${b.toString(16).padStart(2, "0")}`)
      .join(",");
    lines.push(`  ${chunk},`);
  }

  lines.push("]);");
  return lines.join("\n");
}

async function main(): Promise<void> {
  await mkdir(OUTPUT_DIR, { recursive: true });

  // We need a temp directory for the C source files that generateFont etc.
  // write (we don't use them, but the functions expect outputDir).
  const { mkdtempSync } = await import("fs");
  const { tmpdir } = await import("os");
  const tempDir = mkdtempSync(join(tmpdir(), "gbs-assets-"));

  console.log("Generating font tiles...");
  const font = await generateFont(ASSET_DIR, tempDir);

  console.log("Generating soft font tiles...");
  const softFont = await generateSoftFont(ASSET_DIR, tempDir);

  console.log("Generating icon tiles...");
  const icons = await generateIcons(ASSET_DIR, tempDir);

  console.log("Generating default cover tiles...");
  const cover = await generateCover(tempDir);

  const parts = [
    "// Auto-generated by scripts/build-assets.ts. DO NOT EDIT.",
    "// Font, icon, and cover tile data as Uint8Array constants for the web app.",
    "",
    `// Condensed font: ${font.tileData.length} bytes (${font.tileData.length / 16} tiles)`,
    toTsArray("FONT_TILE_DATA", font.tileData),
    "",
    `// Per-character advance widths: ${font.widthData.length} bytes`,
    toTsArray("FONT_WIDTH_DATA", font.widthData),
    "",
    `// Soft font (fixed-width): ${softFont.tileData.length} bytes (${softFont.tileData.length / 16} tiles)`,
    toTsArray("SOFT_FONT_TILE_DATA", softFont.tileData),
    "",
    `// Icon tiles: ${icons.tileData.length} bytes (${icons.tileData.length / 16} tiles)`,
    toTsArray("ICON_TILE_DATA", icons.tileData),
    "",
    `// Default cover tiles: ${cover.tileData.length} bytes (${cover.tileData.length / 16} tiles)`,
    toTsArray("DEFAULT_COVER_TILES", cover.tileData),
    "",
  ];

  const outputPath = join(OUTPUT_DIR, "tile-data.ts");
  await writeFile(outputPath, parts.join("\n"), "utf8");
  console.log(`Written: ${outputPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
